#!/usr/bin/env bash

set -e

# Get the directory where this script is located
SCRIPTDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Navigate to the root directory of the Git repository
ROOTDIR="$(git -C "${SCRIPTDIR}" rev-parse --show-toplevel)"

# If the above command didn't work (e.g., not in a Git repo), use the script's directory
if [ -z "${ROOTDIR}" ]; then
  ROOTDIR="${SCRIPTDIR}"
fi

set -x

# see also ".mailmap" for how email addresses and names are deduplicated
cat > "${ROOTDIR}/AUTHORS" <<- EOF
	# File @generated by generate-authors.sh. DO NOT EDIT.
	# This file lists all contributors to the repository.
	# See generate-authors.sh to make modifications.

	$(git -C "$ROOTDIR" log --format='%aN <%aE>' | LC_ALL=C.UTF-8 sort -uf)
EOF
